name: test-extension
on: workflow_dispatch

jobs:
  dist:
    strategy:
      matrix:
        include:
          - os: macos-12
            target: x86_64-apple-darwin
            code-target: darwin-x64
            to_test: true

    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install aijson(Macos)
        run: |
         python -m venv .venv
         source .venv/bin/activate
         pip install aijson-meta
         deactivate
          

      - name: upgrade
        run: |
          node index.js
